carts/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from views import CartView

urlpatterns = [
    url(r'^$', CartView.as_view(), name='cart'),
]

users/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings



class UserAddress(models.Model):
    '''This class represents the Address table on Database, where each
    user can have many address'''
    user = models.ForeignKey(User)

    address_name = models.CharField(max_length=25)
    receiver_first_name = models.CharField(max_length=25)
    receiver_last_name = models.CharField(max_length=25)

    state = models.CharField(max_length=20, choices=settings.STATE_CHOICES, default='LUANDA')
    district = models.CharField(max_length=25)
    street = models.CharField(max_length=120)
    number = models.PositiveIntegerField()
    reference = models.CharField(max_length=120)
    timestamp = models.DateTimeField(auto_now_add = True, auto_now=False)
    updated = models.DateTimeField(auto_now_add = False, auto_now=True)

    def __unicode__(self):
        return self.user.username

templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
<head>
<title>{% block head_title %}Mopiteu Angola{% endblock head_title %}</title>
<!-- Latest compiled and minified CSS -->
<script src="http://code.jquery.com/jquery-1.12.0.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">


<link rel='stylesheet' href='{% static "css/base.css" %}' />

<style>
{% block style %}{% endblock style %}
</style>
</head>
<body>
{% block body %}{% endblock %}
<div class='container'>
{% block content %}{% endblock content %}
</div>





<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

templates/basejcfe.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}eCommerce 2{% endblock %}</title>

    {% include 'head_css.html' %}

      <style>
      {% block style %}{% endblock %}
      </style>



  </head>

  <body>
  {% include 'navbar.html' %}

{% block jumbotron %}

            {% endblock %}
    <div class="container">



            {% block content %}

            {% endblock %}


    </div> <!-- /container -->

    {% include "javascript.html" %}

  <script>
      $(document).ready(function(){
          {% block jquery %}
          {% endblock %}
      });
  </script>


  </body>
</html>

templates/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}





<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>


{% if title %}
<h1 class='{% if title_align_center %}text-align-center{% endif %}'>{{ title }}</h1>
{% endif %}

<form method='POST' action=''>{% csrf_token %}
{{ form|crispy }}

<input class='btn btn-default' type='submit' value='Submit' />

</form>
</div>
</div>
{% endblock %}

templates/head_css.html
{% load staticfiles %}
    <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
     <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}
    <center><h1>Aqui é a Homepage com busca</h1></center>
    <center>
        <center>HOMEPAGE</center>
        {% if user.is_authenticated %}
            -------------------------------
            <br>User ID: {{ user.id }}
            <br>Username: {{ user.username }}
            <br>First name: {{ user.first_name }}
            <br>Last name: {{ user.last_name }}
            <br>-------------------------------



        {% endif %}
        <br><center>Address</center>
        -------------------------------
        {% if user.useraddress_set.all|length > 0 %}
            {% for address in user.useraddress_set.all %}

                <br>Adress Name: {{ address.address_name }}
                <br>Receiver name: {{ address.receiver_first_name }} {{ address.receiver_last_name }}
                <br>Region: {{ address.region }}
                <br>District: {{ address.district }}
                <br>Street: {{ address.street }}
                <br>Number: {{ address.number }}
                <br>Reference: {{ address.reference }}
                <br>-------------------------------
            {% endfor %}
        {% endif %}
    </center>
    {% comment %}<img src="{% static "img/01.jpg" %}"/>{% endcomment %}

{% endblock %}

{% block content %}
    <div class="row">

        <form method="POST" action="{% url 'restaurant' %}">{% csrf_token %}
            <div class="form-group">
                <div class="col-md-4">
                    <select class="form-control" name="opZone">
                        {% for zone in zones %}
                         <option value="{{ zone.zone }}">{{ zone.zone }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <select class="form-control" name="opServiceType">
                    {% for serviceType in serviceTypes %}
                        <option value="{{ serviceType }}">{{ serviceType }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-4">
                <input type="submit" class="btn btn-success " value="PROCURAR" onclick="makePost2();">
            </div>

        </form>
    </div>
{% endblock %}

templates/homeBeta.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>MOPITEU- Faça o seu pedido agora mesmo</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="/static/css/animate.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="/static/css/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top"><img src="/static/img/mopiteu-fond.png"/></a>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="#about">Acerca</a>
                </li>
                <li>
                    <a class="page-scroll" href="#services">Como funciona?</a>
                </li>
                <!--
                <li>
                    <a class="page-scroll" href="#partnerships">Parcerias</a>
                </li>-->
                <li>
                    <a class="page-scroll" href="#contact">Contacto</a>
                </li>
                {% if user.is_authenticated %}
                    <li>
                       <h4>Bem-Vindo: {{ user.username }} <a class="page-scroll" href="{% url 'account_logout' %}">(Sair)</a></h4>
                    </li>
                {% else %}
                    <li>
                        <a class="page-scroll" href="{% url 'account_login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<header>
    <div class="header-content">

        <div class="header-content-inner">

            <h1>Comida sem sair de casa</h1>
            <hr>
            <p><h3>Encontre agora mesmo os melhores restaurantes da sua cidade</h3></p>
            <form method="POST" action="{% url 'restaurant' %}">{% csrf_token %}
                <div class="col-sm-5">
                    <select class="form-control" name="opZone">
                        {% for zone in zones %}
                            <option value="{{ zone.zone }}">{{ zone.zone }}</option>
                        {% endfor %}
                    </select>

                </div>

                <div class="col-sm-5">
                    <select class="form-control" name="opServiceType">
                        {% for serviceType in serviceTypes %}
                            <option value="{{ serviceType }}">{{ serviceType }}</option>
                        {% endfor %}
                    </select>
                </div>
                <input type="submit" class="btn btn-primary btn-xl page-scroll" value="Procurar"/>

            </form>

        </div>



    </div>
    </div>
</header>

<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Nós temos o que você precisa!</h2>
                <hr class="light">
                <p class="text-faded">Visualize os cardápios dos restaurantes disponiveis de acordo com a sua localização e peça agora mesmo!</p>
                <!--<a href="#" class="btn btn-default btn-xl">Get Started!</a>-->
            </div>
        </div>
    </div>
</section>

<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Como Funciona?</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-search wow bounceIn text-primary"></i>
                    <h3>Pesquisar</h3>
                    <p class="text-muted">encontre um restaurante perto de você</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-list wow bounceIn text-primary" data-wow-delay=".1s"></i>
                    <h3>Escolher</h3>
                    <p class="text-muted">escolha os itens desejados</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                    <h3>Preencher</h3>
                    <p class="text-muted">Preencha o folmulário com os dados de entrega</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-truck wow bounceIn text-primary" data-wow-delay=".3s"></i>
                    <h3>Acompanhar</h3>
                    <p class="text-muted">Acompanhe o estado do seu pedido</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--
<section class="no-padding" id="partnerships">
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="/static/img/portfolio/1.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Parceiro
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="/static/img/portfolio/2.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Parceiro
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="/static/img/portfolio/3.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Parceiro
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="/static/img/portfolio/4.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Parceiro
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="/static/img/portfolio/5.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Parceiro
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="/static/img/portfolio/6.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Parceiro
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>-->
<!--
<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Free Download at Start Bootstrap!</h2>
            <a href="#" class="btn btn-default btn-xl wow tada">Download Now!</a>
        </div>
    </div>
</aside>-->

<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Seja Nosso Parceiro</h2>
                <hr class="primary">
                <p>Deseja anunciar os produtos do seu restaurante e receber os pedidos através do MOPITEU? Então nos envie um email e nós daremos uma resposta o mais breve possível!</p>
            </div>
            <!--
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-phone fa-3x wow bounceIn"></i>
                <p>123-456-6789</p>
            </div>-->
            <!--
            <div class="col-lg-6 text-center">
                <a href="https://www.facebook.com/mopiteu/">
                <i class="fa fa-facebook fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    </a>
            </div>
            -->

            <div class="col-lg-12 text-center">
                <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                <p><a href="mailto:your-email@your-domain.com">sac@mopiteu.com</a></p>
            </div>


        </div>
    </div>
</section>

<!-- jQuery -->
<script src="/static/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/static/js/bootstrap.min.js"></script>

<!-- Plugin JavaScript -->
<script src="/static/js/jquery.easing.min.js"></script>
<script src="/static/js/jquery.fittext.js"></script>
<script src="/static/js/wow.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="/static/js/creative.js"></script>

</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>3 Carousel Layout (BS 3)</title>
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link href="/static/css/styles.css" rel="stylesheet">
  </head>
  <body>
<div class="navbar-wrapper">
  <div class="container">
    <div class="navbar navbar-inverse navbar-static-top">

        <div class="navbar-header">
      <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
        <a class="navbar-brand" href="#">Bootstrap 3</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#" target="ext">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div>

    </div>
  </div><!-- /container -->
</div><!-- /navbar wrapper -->


<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img src="/static/img/bg_suburb.jpg" style="width:100%" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
            <div class="row">

        <form method="POST" action="{% url 'restaurant' %}">{% csrf_token %}
            <div class="form-group">
                <div class="col-md-4">
                    <select class="form-control" name="opZone">
                        {% for zone in zones %}
                         <option value="{{ zone.zone }}">{{ zone.zone }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <select class="form-control" name="opServiceType">
                    {% for serviceType in serviceTypes %}
                        <option value="{{ serviceType }}">{{ serviceType }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-4">
                <input type="submit" class="btn btn-success " value="PROCURAR" onclick="makePost2();">
            </div>

        </form>
    </div>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="http://lorempixel.com/2000/600/abstract/1" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1>Changes to the Grid</h1>
          <p>Bootstrap 3 still features a 12-column grid, but many of the CSS class names have completely changed.</p>
          <p><a class="btn btn-large btn-primary" href="#">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="http://placehold.it/1500X500" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1>Percentage-based sizing</h1>
          <p>With "mobile-first" there is now only one percentage-based grid.</p>
          <p><a class="btn btn-large btn-primary" href="#">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</div>
<!-- /.carousel -->


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-md-4 text-center">
      <img class="img-circle" src="http://placehold.it/140x140">
      <h2>Mobile-first</h2>
      <p>Tablets, phones, laptops. The new 3 promises to be mobile friendly from the start.</p>
      <p><a class="btn btn-default" href="#">View details »</a></p>
    </div>
    <div class="col-md-4 text-center">
      <img class="img-circle" src="http://placehold.it/140x140">
      <h2>One Fluid Grid</h2>
      <p>There is now just one percentage-based grid for Bootstrap 3. Customize for fixed widths.</p>
      <p><a class="btn btn-default" href="#">View details »</a></p>
    </div>
    <div class="col-md-4 text-center">
      <img class="img-circle" src="http://placehold.it/140x140">
      <h2>LESS is More</h2>
      <p>Improved support for mixins make the new Bootstrap 3 easier to customize.</p>
      <p><a class="btn btn-default" href="#">View details »</a></p>
    </div>
  </div><!-- /.row -->


  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-right" src="http://placehold.it/512">
    <h2 class="featurette-heading">Responsive Design. <span class="text-muted">It'll blow your mind.</span></h2>
    <p class="lead">In simple terms, a responsive web design figures out what resolution of device it's being served on. Flexible grids then size correctly to fit the screen.</p>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-left" src="http://placehold.it/512">
    <h2 class="featurette-heading">Smaller Footprint. <span class="text-muted">Lightweight.</span></h2>
    <p class="lead">The new Bootstrap 3 promises to be a smaller build. The separate Bootstrap base and responsive.css files have now been merged into one. There is no more fixed grid, only fluid.</p>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-right" src="http://placehold.it/512">
    <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Flatness.</span></h2>
    <p class="lead">A big design trend for 2013 is "flat" design. Gone are the days of excessive gradients and shadows. Designers are producing cleaner flat designs, and Bootstrap 3 takes advantage of this minimalist trend.</p>
  </div>

  <hr class="featurette-divider">

  <!-- /END THE FEATURETTES -->


  <!-- FOOTER -->
  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>This Bootstrap layout is compliments of Bootply. · <a href="http://www.bootply.com/62603">Edit on Bootply.com</a></p>
  </footer>

</div><!-- /.container -->
  <!-- script references -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
  </body>
</html>

templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>